CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "name" varchar,
  "inserted_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "authentication" (
  "user_id" int PRIMARY KEY,
  "password" varchar,
  "google_id" varchar,
  "github_id" varchar
);

CREATE TABLE "groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "inserted_at" timestamp
);

CREATE TABLE "user_groups" (
  "user_id" int,
  "group_id" int,
  "screen_time_goal" int,
  "inserted_at" timestamp
);

CREATE TABLE "user_details" (
  "user_id" int PRIMARY KEY,
  "bio" text
);

CREATE TABLE "screen_time" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "total_time" int,
  "inserted_at" timestamp
);

ALTER TABLE "authentication" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "user_groups" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "user_groups" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");
ALTER TABLE "user_details" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "screen_time" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id"); 