DROP TABLE IF EXISTS screen_times;
DROP TABLE IF EXISTS user_groups;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS authentications;
DROP TABLE IF EXISTS users;

create table users
(
    id              integer generated by default as identity
        primary key,
    email           varchar,
    name            varchar,
    inserted_at     timestamp    default now()                                                                             not null,
    updated_at      timestamp,
    profile_picture varchar(255) default 'https://s3.amazonaws.com/37assets/svn/765-default-avatar.png'::character varying not null
);

create table authentications
(
    user_id   integer not null
        constraint authentication_pkey
            primary key
        constraint authentication_user_id_fkey
            references users,
    password  varchar,
    google_id varchar,
    github_id varchar
);

create table groups
(
    id               integer generated by default as identity
        primary key,
    name             varchar,
    inserted_at      timestamp default now() not null,
    code             varchar                 not null,
    stake            double precision,
    screen_time_goal integer
);

create table user_groups
(
    user_id     integer
        references users,
    group_id    integer
        references groups,
    inserted_at timestamp default now() not null,
    id          serial
);

create table screen_times
(
    id             integer generated by default as identity
        constraint screen_time_pkey
            primary key,
    user_id        integer
        constraint screen_time_user_id_fkey
            references users,
    submitted_time double precision,
    inserted_at    timestamp default now(),
);
